package font

// GlyphWidth is the width of each character in the font.
const GlyphWidth = 5

// GlyphHeight is the height of each character in the font (matches display height).
const GlyphHeight = 7

// GlyphSpacing is the number of blank columns between characters.
const GlyphSpacing = 1

// Glyph represents a single character as a 7x5 pixel bitmap.
// Non-zero values (0xFF) mark lit pixels; Render scales by brightness.
type Glyph [GlyphHeight][GlyphWidth]byte

const f = 0xFF // lit pixel marker

// glyphs maps runes to their glyph bitmaps.
// Letters are 5 pixels tall, centered vertically (rows 1-5, rows 0 and 6 blank).
var glyphs = map[rune]Glyph{
	'a': {
		{},
		{0, f, f, f, 0},
		{f, 0, 0, 0, f},
		{f, f, f, f, f},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{},
	},
	'b': {
		{},
		{f, f, f, f, 0},
		{f, 0, 0, 0, f},
		{f, f, f, f, 0},
		{f, 0, 0, 0, f},
		{f, f, f, f, 0},
		{},
	},
	'c': {
		{},
		{0, f, f, f, 0},
		{f, 0, 0, 0, 0},
		{f, 0, 0, 0, 0},
		{f, 0, 0, 0, 0},
		{0, f, f, f, 0},
		{},
	},
	'd': {
		{},
		{f, f, f, 0, 0},
		{f, 0, 0, f, 0},
		{f, 0, 0, f, 0},
		{f, 0, 0, f, 0},
		{f, f, f, 0, 0},
		{},
	},
	'e': {
		{},
		{f, f, f, f, f},
		{f, 0, 0, 0, 0},
		{f, f, f, 0, 0},
		{f, 0, 0, 0, 0},
		{f, f, f, f, f},
		{},
	},
	'f': {
		{},
		{f, f, f, f, f},
		{f, 0, 0, 0, 0},
		{f, f, f, 0, 0},
		{f, 0, 0, 0, 0},
		{f, 0, 0, 0, 0},
		{},
	},
	'g': {
		{},
		{0, f, f, f, 0},
		{f, 0, 0, 0, 0},
		{f, 0, f, f, f},
		{f, 0, 0, 0, f},
		{0, f, f, f, 0},
		{},
	},
	'h': {
		{},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{f, f, f, f, f},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{},
	},
	'i': {
		{},
		{0, f, f, f, 0},
		{0, 0, f, 0, 0},
		{0, 0, f, 0, 0},
		{0, 0, f, 0, 0},
		{0, f, f, f, 0},
		{},
	},
	'j': {
		{},
		{0, 0, f, f, f},
		{0, 0, 0, f, 0},
		{0, 0, 0, f, 0},
		{f, 0, 0, f, 0},
		{0, f, f, 0, 0},
		{},
	},
	'k': {
		{},
		{f, 0, 0, f, 0},
		{f, 0, f, 0, 0},
		{f, f, 0, 0, 0},
		{f, 0, f, 0, 0},
		{f, 0, 0, f, 0},
		{},
	},
	'l': {
		{},
		{f, 0, 0, 0, 0},
		{f, 0, 0, 0, 0},
		{f, 0, 0, 0, 0},
		{f, 0, 0, 0, 0},
		{f, f, f, f, f},
		{},
	},
	'm': {
		{},
		{f, 0, 0, 0, f},
		{f, f, 0, f, f},
		{f, 0, f, 0, f},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{},
	},
	'n': {
		{},
		{f, 0, 0, 0, f},
		{f, f, 0, 0, f},
		{f, 0, f, 0, f},
		{f, 0, 0, f, f},
		{f, 0, 0, 0, f},
		{},
	},
	'o': {
		{},
		{0, f, f, f, 0},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{0, f, f, f, 0},
		{},
	},
	'p': {
		{},
		{f, f, f, f, 0},
		{f, 0, 0, 0, f},
		{f, f, f, f, 0},
		{f, 0, 0, 0, 0},
		{f, 0, 0, 0, 0},
		{},
	},
	'q': {
		{},
		{0, f, f, f, 0},
		{f, 0, 0, 0, f},
		{f, 0, f, 0, f},
		{f, 0, 0, f, 0},
		{0, f, f, 0, f},
		{},
	},
	'r': {
		{},
		{f, f, f, f, 0},
		{f, 0, 0, 0, f},
		{f, f, f, f, 0},
		{f, 0, f, 0, 0},
		{f, 0, 0, f, 0},
		{},
	},
	's': {
		{},
		{0, f, f, f, 0},
		{f, 0, 0, 0, 0},
		{0, f, f, f, 0},
		{0, 0, 0, 0, f},
		{0, f, f, f, 0},
		{},
	},
	't': {
		{},
		{f, f, f, f, f},
		{0, 0, f, 0, 0},
		{0, 0, f, 0, 0},
		{0, 0, f, 0, 0},
		{0, 0, f, 0, 0},
		{},
	},
	'u': {
		{},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{0, f, f, f, 0},
		{},
	},
	'v': {
		{},
		{f, 0, 0, 0, f},
		{f, 0, 0, 0, f},
		{0, f, 0, f, 0},
		{0, f, 0, f, 0},
		{0, 0, f, 0, 0},
		{},
	},
	'w': {
		{},
		{f, 0, 0, 0, f},
		{f, 0, f, 0, f},
		{f, 0, f, 0, f},
		{f, f, 0, f, f},
		{f, 0, 0, 0, f},
		{},
	},
	'x': {
		{},
		{f, 0, 0, 0, f},
		{0, f, 0, f, 0},
		{0, 0, f, 0, 0},
		{0, f, 0, f, 0},
		{f, 0, 0, 0, f},
		{},
	},
	'y': {
		{},
		{f, 0, 0, 0, f},
		{0, f, 0, f, 0},
		{0, 0, f, 0, 0},
		{0, 0, f, 0, 0},
		{0, 0, f, 0, 0},
		{},
	},
	'z': {
		{},
		{f, f, f, f, f},
		{0, 0, 0, f, 0},
		{0, 0, f, 0, 0},
		{0, f, 0, 0, 0},
		{f, f, f, f, f},
		{},
	},
	' ': {},
}
